### ISSUE TITLE
希望能支持rtc时间，存档相关

### ISSUE THREAD

**Issue by nenge123** [44670/vba-next-wasm#1]
电池存档（或即时存档）可以下载下来，或者载入。

支持rtc时间。

**Comment by 44670** [comment]
现在可以下载/还原存档啦。
试了一下我们的太阳，是支持rtc时间的。其它游戏还需要测试。

**Comment by nenge123** [comment]
有新版本了？
1.3并好像不支持rtc，下载的存档也是无效，其他模拟器也不能读取。
储存的时候是uint8array255.255结果读取文件的时候变成unit8array50:53￼。
于是我先把储存255转换成字符，再去还原，倒是成功读取档案。

这是基于你的代码修改。
https://nenge.net/emulator/app/vba-wasm/

**Comment by nenge123** [comment]
万能模拟器里面的核心好像只有vbam支持rtc

**Comment by 44670** [comment]
> 255.255结

这个是之前的版本的缺陷，Ver. 20210114已经修复。存档格式其它模拟器应该是不能读的，不过简单处理一下应该就ＯＫ。
rtc的支持似乎取决于游戏，我再看看。

**Comment by nenge123** [comment]
> > 255.255结
> 
> 
> 
> 这个是之前的版本的缺陷，Ver. 20210114已经修复。存档格式其它模拟器应该是不能读的，不过简单处理一下应该就ＯＫ。
> 
> rtc的支持似乎取决于游戏，我再看看。
> 
> 
> 
> 

我测试的游戏是口袋妖怪 特别篇赤，这个游戏需要真实时间触发某些任务。

**Comment by nenge123** [comment]
太棒了！


我尝试上传retroarch里面的存档，结果成功读取记录了！

![image](https://user-images.githubusercontent.com/16117315/104796183-e4f49800-57ee-11eb-8f3d-33cd2bf083ee.png)
