### ISSUE TITLE
建议提供接口说明文档

### ISSUE THREAD

**Issue by nenge123** [44670/vba-next-wasm#2]
希望在说明文档写出一些接口函数说明。

** 其他 **
加载wasm方式希望可以在外部进行，或者外部自定义方式读取并且加载。因为当我想特殊方式加载wasm。例如我把a.out.js，a.out.wasm扔进压缩包里，利用jszip解压并且执行。压缩后，原本500kb的wasm会压缩到70kb，加速传输，或者本地保存下来。

**Comment by 44670** [comment]
针对第二个需求，建议直接在http服务器上配置压缩（目前已经用Brotli压缩了）。
js-wasm的内部接口随时都可能会修改，不建议作为外部库直接使用。

**Comment by 44670** [comment]
未来有可能会上线离线功能的支持，这样即使是在飞行模式下也可以正常游玩。不过可能需要再过一段时间。

**Comment by nenge123** [comment]
离线功能？如果添加到主屏幕，只要不关闭离线玩问题不大，会一直保留状态。

如果是指游戏储存下来，完全可以吧游戏文件储存到indexdb，实现最近玩过的游戏。或者历史玩过的游戏。就像一个独立app一样的存在～

不过要实现大众需求，金手指支持少不了。加速和rtc也有一定的需求。

**Comment by 44670** [comment]
理想的目标是像其它的app一样，关闭后即使是离线环境打开也能一直玩。实现这个需要serviceworker。加速已经支持了（按Turbo按钮），rtc好像还有问题。

**Comment by nenge123** [comment]
要不要换成vbam 这个核心不但支持gb gbc 还支持rtc，显示模式

**Comment by 44670** [comment]
这个其实就是vbam，也确实支持rtc，但是有的游戏不兼容，比较谜

**Comment by nenge123** [comment]
这个是vba-next和vbam不一样吧。

**Comment by 44670** [comment]
是基于vba-m进一步改进的分支

**Comment by nenge123** [comment]
这样啊，我在retroarch模拟器里面直接用vbam.如果用next一样不能使用rtc.在vbam里面默认不开启rtc，需要设置打开才有效。那么在next里面会不会也要给它提供时间才生效？

**Comment by nenge123** [comment]
大大大 会纯js转码吗？

我遇到一个问题，运行被压缩后的gba问题，jszip解压含有中文文件名的gba文件，会显示乱码。是两个ascii的字（五个汉字，显示出十个字符）。但是不知道怎么转换成正常中文，用过其他转码js不怎么成功。

**Comment by nenge123** [comment]
偶然间我上传存档时，居然显示rtc。当时我的js有问题，gameid保留上个游戏值，存在未定义等。
