### ISSUE TITLE
金手指和网上搜到的有什么不同

### ISSUE THREAD

**Issue by nenge123** [44670/vba-next-wasm#5]
或者应该怎么转化。

离线缓存网页直接用 manifest就可以实现了

**Comment by 44670** [comment]
https://github.com/Ensiss/pokebot/wiki/GBA-Memory-Map
参考这个

**Comment by nenge123** [comment]
表示完全看不懂……，retroarch也支持金手指，也支持那种gs代码，它是怎么转化成地址的？

**Comment by nenge123** [comment]
现在就差金手指没搞明白～

蓝牙手柄我也测试好了，建议把wasm加载到indexdb吧，不是服务器弄个zip完事，加载速度真的快很多！

**Comment by nenge123** [comment]
vbam里面有gs金手指代码转换，会考虑增加吗？

**Comment by 44670** [comment]
感觉好麻烦哦，我回头试试看。
有没有金手指数据库推荐？

**Comment by nenge123** [comment]
我在vba电脑模拟器测试了
绿宝石美版。
开启：0146DCEA3E32A31D
03007E28:0001 妙蛙种子

复制这段内容后打开百度网盘App，操作更方便哦。
链接：https://pan.baidu.com/s/1g3_lRmo1LX9mn7LbIafUVQ 
提取码：gg4X 

- - - - - - - 
即时存档可以没有，但是金手指也实现几乎跟电脑版没区别了。

**Comment by nenge123** [comment]
发现一个可爱又蛋疼的网站，emulatorjs
他也是以retroarch的核心以wasm方式，我研究它的函数发现居然有金手指功能，功能方面也很不错。gba核心里面的滤镜都有。

但是不可以手动上传游戏，不知道为什么用blob地址就异常，猜测是他要把文件分割，还检查是不是http开头，代码经过交叉加密。阅读理解难

最后只能在线玩服务器上的游戏。
