### ISSUE TITLE
请教一下加速功能总是失灵是为啥呀？

### ISSUE THREAD

**Issue by lzhzzz1** [44670/vba-next-wasm#8]

**Comment by lzhzzz1** [comment]
大佬，我最近加速点击了总是没有反应的是因为啥？

**Comment by nenge123** [comment]
> 大佬，我最近加速点击了总是没有反应的是因为啥？

如果不会修改js那就去我改好的[版本](https://nenge.net/emulator/app/vba-wasm/)

index.html查找handleTouch,
for ( var k in keyStste在前面加

var elm=event.target,k = elm.getAttribute("data-k");
if(k=="turbo"){
keyState["turbo][2] = keyState["turbo][2]?false:true;
  return setTurboMode(keyState["turbo][2]);
}

**Comment by lzhzzz1** [comment]
爱您，第一次接触不会😂，太感谢体贴了！

**Comment by lzhzzz1** [comment]
> > 大佬，我最近加速点击了总是没有反应的是因为啥？
> 
> 如果不会修改js那就去我改好的[版本](https://nenge.net/emulator/app/vba-wasm/)
> 
> index.html查找handleTouch,
> for ( var k in keyStste在前面加
> 
> var elm=event.target,k = elm.getAttribute("data-k");
> if(k=="turbo"){
> keyState["turbo][2] = keyState["turbo][2]?false:true;
> return setTurboMode(keyState["turbo][2]);
> }

**Comment by lzhzzz1** [comment]
还有一个小问题，就是我将网页添加到主屏幕以后加速就失灵啦，还是引用这个办法吗？

**Comment by nenge123** [comment]
点击上面的版本。蓝色字

**Comment by lzhzzz1** [comment]
我是尝试了蓝色字的版本，再将那个页面添加到主屏幕以后加速又失灵了，但是浏览器内是正常的

**Comment by nenge123** [comment]
不可能，你是手机还是平板？
我自己手机都正常，我还把蓝牙手柄给支持了

**Comment by lzhzzz1** [comment]
我是手机，14.3的版本，真哒，我尝试了好几次，这次评论前我还尝试了一下，也不行，就是您更新过的版本

**Comment by lzhzzz1** [comment]
可能就我的问题，我只要切出去再回来加速也同样失效……

**Comment by nenge123** [comment]
你直接在浏览器玩吧，只要不清空浏览器缓存就不会记录消失。不影响使用

**Comment by 44670** [comment]
那个加速按钮是要持续按住才能有效的。
